apiVersion: getambassador.io/v2
kind: Mapping
metadata:
  annotations:
    getambassador.io/resource-changed: 'true'
  managedFields:
    - apiVersion: getambassador.io/v2
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:getambassador.io/resource-changed': {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
        'f:spec':
          .: {}
          'f:prefix': {}
          'f:service': {}
      manager: kubectl
      operation: Update
      time: '2020-01-01T13:02:54Z'
  name: es-gateway
  namespace: default
spec:
  prefix: /es/
  service: 'es-hpd-es-http:9200'
  timeout_ms: 6000
  idle_timeout_ms: 60000
  connect_timeout_ms: 60000
  host: apies.tonydeveloper.com
  tls: secured
---
apiVersion: getambassador.io/v2
kind:  TLSContext
metadata:
  name: secured
spec:
  hosts:
  - apies.tonydeveloper.com
  secret: hpd-cacert
